"""empty message

Revision ID: 032f6eee18a5
Revises: 
Create Date: 2024-04-15 15:09:27.195320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '032f6eee18a5'
down_revision = None
branch_labels = None
depends_on = None
 

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
